name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Télécharger le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Installer Java (FIX ICI ✅)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Installer sonar-scanner
      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y sonar-scanner

      # 4️⃣ Lancer analyse SonarQube
      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Git \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
